name: Provision Azure Infrastructure with HCP Terraform

on:
  push:
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configurar o diretório correto e inicializar o Terraform
      - name: Set up Terraform
        run: |
          cd terraform
          terraform init

      # Step 3: Validar o código do Terraform
      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      # Step 4: Executar o plano do Terraform
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=tfplan

      # Step 5: Aplicar o plano do Terraform (opcional)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: |
          cd terraform
          terraform apply -auto-approve tfplan
