name: Provision Infrastructure with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configurar autenticação do Terraform
      - name: Configure Terraform authentication
        run: |
          mkdir -p ~/.terraform.d
          echo '{
            "credentials": {
              "app.terraform.io": {
                "token": "'"${{ secrets.HCP_TERRAFORM_TOKEN }}"'"
              }
            }
          }' > ~/.terraform.d/credentials.tfrc.json

      # Step 3: Inicializar o Terraform
      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init
